name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev build-essential openjdk-11-jdk zlib1g-dev libffi-dev
        pip3 install --upgrade buildozer cython

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: bin/*.apk