name: Buildozer APK

# Permet de lancer le workflow manuellement
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer toutes les dépendances nécessaires
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 python3-pip \
            openjdk-17-jdk unzip zlib1g-dev libncurses5-dev libffi-dev \
            libssl-dev libsqlite3-dev ccache
          pip install --user buildozer cython

      # Compiler l'APK avec Buildozer
      - name: Build APK
        run: |
          buildozer android debug

      # Uploader l'APK généré comme artifact
      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: bin/*.apk
